# Evaluation partition.
eval:
  _target_: src.datasets.ASVspoofDataset
  name: eval
  protocol_path: ${dataset_root}/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
  audio_dir: ${dataset_root}/ASVspoof2019_LA_eval/flac
  max_len: 64000
  instance_transforms: ${transforms.instance_transforms.inference}
