defaults:
  - model: lcnn
  - writer: wandb
  - metrics: asvspoof
  - datasets: asvspoof
  - dataloader: asvspoof
  - transforms: asvspoof
  - loss_function: ce
  - _self_

dataset_root: /kaggle/input/asvspoof2019/LA

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 0  # AdamW(wd=0) == Adam
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5  # halve lr
  step_size: 5000  # every 10 epochs (10 x epoch_len=500)

writer:
  project_name: "asvspoof_lcnn"
  run_name: "lcnn_baseline"

trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: 500
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: False
  monitor: "min val_EER"
  save_period: 2  # dense checkpoints -> fine-grained eval sweep (dev EER saturates)
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
